### ISSUE TITLE
Error at line 30 on Mac

### ISSUE THREAD

**Issue by mattanorak** [dev-est/tuya_tray#1]
After following the instructions, intalling the pre-reqs, I ran:
`python tuya-tray.py`

The following came back:
`File "tuya-tray.py", line 30
    menus[f"{j}_Action"] = menu.addMenu(j)
                      ^
SyntaxError: invalid syntax`

(Sorry, it doesn't show here, but the ^ is pointing to the quote mark to the left of `] = menu.addMenu(j)`

**Comment by dev-est** [comment]
Hey @mattanorak,

I just tested the code on a Macbook and it seemed to work fine, it must be throwing this error in response to no devices being found. Can I just double check that the line of code your editing looks like this if you aren't storing your variables as an environment:

`api.init('TUYA_LOGIN', 'TUYA_PASSWORD' ,"44","tuya")
`
If you could just remove the os.get_environment brackets and rerun let me know what the outcome of that is

**Comment by mattanorak** [comment]
Hi there.

I modified it so that I just have:
`api.init('MYUSERID', 'MYPASSWORD' ,"44","smart_life")`

When I run it, I get the following:

Traceback (most recent call last):
  File "/Users/matt/Desktop/tuya_tray-master/tuya-tray.py", line 4, in <module>
    from tuyapy import TuyaApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tuyapy/__init__.py", line 2, in <module>
    from .tuyaapi import TuyaApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tuyapy/tuyaapi.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by dev-est** [comment]
Hey @mattanorak 

In the terminal if you could just run 

`pip install requests`

and then run the code hopefully that should fix that issue!

**Comment by mattanorak** [comment]
Genius!  Thank you!  That works.
Are there any plans to include smart sockets in this, too?  I've been looking for something like this for a long time and this is just fantastic!

Also, by changing the line:
`devices = dict((i.name(),i) for i in device_id if i.obj_type == 'light')`
to:
`devices = dict((i.name(),i) for i in device_id if i.obj_type == 'light' or i.obj_type == 'switch')`
I can now see all my devices at once!

Nice work, @dev-est !  Very much looking forward to the additions.
