### ISSUE TITLE
[enhancement] Turn On/Off All

### ISSUE THREAD

**Issue by dvdlm** [dev-est/tuya_tray#3]
Feature proposal:
2 buttons added to menu: (Turn On All) & (Turn Off All), and perhaps a flag within tuya_tray.py to enable or disable these buttons.

![image](https://user-images.githubusercontent.com/47398685/97505377-0f446100-1936-11eb-8124-4135a16e23a7.png)

I have many lights, all within one room that I would like to turn on and off at the same time. I recognize though that some people might have lights throughout their house and this button would therefore be useless to them - so this button would be able to be enabled or disabled by a flag in the code.

If you think this idea sounds ok @dev-est I can get to work on starting another pull request?

**Comment by dev-est** [comment]
Hey @dvdlm,

This would be a cool feature, I guess would just be something that is by default commented out and can be enabled by users. Annoying thing is that we can't query by rooms and devices in rooms if you've set that up on the app using the Tuyapy package, so will look into moving to more direct requests to their native API.

**Comment by dev-est** [comment]
Hey @dvdlm 

I've just added this functionality on the latest commit where all lights are grouped together!
