### ISSUE TITLE
Unable to launch from terminal (Mac)

### ISSUE THREAD

**Issue by mattanorak** [dev-est/tuya_tray#6]
I can launch the app fine from Python launcher, but if I want to run it from command line (say, for example, to execute at startup), I type the following:

`python3 /Users/matt/tuyatray/tuya-tray.py`

I then get back the following:
```
Traceback (most recent call last):
  File "/Users/matt/tuyatray/tuya-tray.py", line 94, in <module>
    tray = SystemTrayIcon()
  File "/Users/matt/tuyatray/tuya-tray.py", line 21, in __init__
    self.initUI()
  File "/Users/matt/tuyatray/tuya-tray.py", line 51, in initUI
    with open('config.json') as config:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
```
Looks as if I need to tell it where the config.json is - but it's in the same directory as tuya-tray.py -  I think this might be something t do with relative paths, but I can't quite work it out...

Note: I **can** get it to work if I add the following in the main tuya-tray.py file where the config is called:
`with open('/Users/matt/tuyatray/config.json') as config:`
same for the path to the lightbulb.jpg file (otherwise it won't show if run from the terminal command)

How can this be changed in the code so that it looks at the directory relative to tuya-tray.py (other than hard coding it!)?

Thanks.
Matt

**Comment by dev-est** [comment]
Hey @mattanorak 

Going to do some research about this now, as far as I know a kinda quick solution is to cd to your directory 

`cd /Users/matt/tuyatray/` and then from there do `python3 tuya-tray.py`

**Comment by mattanorak** [comment]
That works!  Good enough for me!   Thanks!
