### ISSUE TITLE
receiving "user/pwd error" message

### ISSUE THREAD

**Issue by sebastianet** [dev-est/tuya_tray#7]
I use your code, edit "config.json", but receive
tuyapy.tuyaapi.TuyaAPIException: Get accesstoken failed. Username or password error!

I copy and paste the user and pwd from config.json onto "https://www.tuya.com/" and they work perfect.
Country code is "34" for Spain, as my devices are in "Europe" - I see then in the IOT platform
Tested both 'tuya' and 'smart_life' in the APP field, no luck

What am I doing wrong ?

**Comment by dev-est** [comment]
Hi, as far as I am aware the website and the application login fields are not connected. 

I’ve just tried logging into the website using my username and password for the app and it doesn’t work. 

The error you’re receiving is correct in that case, meaning the password or email you’re using isn’t the correct one. I would suggest you reset the password on the application or double check the email you’re using!

**Comment by sebastianet** [comment]
OK - if the usr/pwd are not the same, it explains all.
I did change my password (to remove the special characters) and it works OK in the web, but not in the python.
**Now, the big question : how do I generate usr/pwd to be used in your python ?**

**Comment by sebastianet** [comment]
I got it running . the usr/pwd are from Smart Life configuration, not tuya cloud
